import "dotenv/config";
import { Agent,run,tool,webSearchTool } from "@openai/agents";
import { z } from "zod";
import { appendLedger,spentLast24h,summarizeLedger,goalStatus } from "./ledger.js";
import { walletSnapshot,treasurySnapshot,deployContract } from "./blockchain.js";
import { saveProduct,productIdFromSlug,salesMetrics,setProductActive,getProduct } from "./products.js";
import { setOnchainProduct,resolvedGatewayAddress } from "./gateway.js";
import { publishMarketing } from "./marketing.js";
import { maxDailySpendUsd,maxExperimentUsd,targetUsd,targetDate,publicBaseUrl,networkName,allowMainnet,allowOnchainAssetLaunches } from "./config.js";

const walletTool=tool({name:"wallet_snapshot",description:"Read operational agent wallet and treasury balances.",parameters:z.object({}),execute:async()=>JSON.stringify({agent:await walletSnapshot(),treasury:await treasurySnapshot(),gateway:resolvedGatewayAddress()??null})});
const ledgerTool=tool({name:"ledger_summary",description:"Read real costs, paid sales, P&L and goal pace.",parameters:z.object({}),execute:async()=>JSON.stringify({ledger:summarizeLedger(),goal:goalStatus(),sales:salesMetrics()})});
const noteTool=tool({name:"record_note",description:"Record a business decision or observation.",parameters:z.object({label:z.string().min(1).max(4000)}),execute:async({label})=>{appendLedger({kind:"note",usd:0,label});return "recorded";}});
const costTool=tool({name:"record_cost",description:"Record an ACTUALLY incurred cost. Never record hypothetical spend.",parameters:z.object({usd:z.number().positive(),label:z.string().min(1),txHash:z.string().optional()}),execute:async({usd,label,txHash})=>{if(usd>maxExperimentUsd)throw new Error(`Per-experiment cap $${maxExperimentUsd}`);if(spentLast24h()+usd>maxDailySpendUsd)throw new Error(`24h spend cap $${maxDailySpendUsd}`);appendLedger({kind:"cost",usd,label,txHash});return JSON.stringify(summarizeLedger());}});
const productTool=tool({name:"create_or_update_digital_product",description:"Create a downloadable digital product and register its USDC checkout price.",parameters:z.object({slug:z.string().regex(/^[a-z0-9-]{3,60}$/),title:z.string().min(3).max(120),description:z.string().min(20).max(1200),priceUsd:z.number().min(1).max(10000),content:z.string().min(100).max(80000),format:z.enum(["markdown","text","html","json","csv"]),language:z.string().min(2).max(40),targetMarket:z.string().min(2).max(100),tags:z.array(z.string().min(1).max(40)).max(12)}),execute:async(input)=>{if(!resolvedGatewayAddress())throw new Error("Checkout gateway not ready yet.");const id=productIdFromSlug(input.slug) as `0x${string}`;const txHash=await setOnchainProduct(id,input.priceUsd,true);const p=saveProduct({...input,active:true});appendLedger({kind:"note",usd:0,label:`Product live: ${p.title} | ${p.targetMarket}/${p.language} | ${publicBaseUrl}/p/${p.slug}`,txHash,productId:p.id,market:p.targetMarket,language:p.language});return JSON.stringify({...p,checkoutUrl:`${publicBaseUrl}/p/${p.slug}`,txHash});}});
const lifecycleTool=tool({name:"set_product_active",description:"Activate or kill a product using sales evidence.",parameters:z.object({slug:z.string(),active:z.boolean(),reason:z.string().min(10).max(500)}),execute:async({slug,active,reason})=>{const p=getProduct(slug);if(!p)throw new Error("Product not found");if(resolvedGatewayAddress())await setOnchainProduct(p.id as `0x${string}`,p.priceUsd,active);const updated=setProductActive(slug,active);appendLedger({kind:"note",usd:0,label:`${active?"ACTIVATED":"KILLED"} ${slug}: ${reason}`,productId:p.id});return JSON.stringify(updated);}});
const marketingTool=tool({name:"publish_marketing_post",description:"Publish or queue truthful marketing in the target market's natural language.",parameters:z.object({productSlug:z.string(),channel:z.enum(["telegram","discord","x","linkedin","facebook","instagram","generic"]),copy:z.string().min(20).max(3000),language:z.string().min(2).max(40),targetMarket:z.string().min(2).max(100)}),execute:async(input)=>JSON.stringify(await publishMarketing(input))});
const tokenTool=tool({name:"deploy_utility_token",description:"Deploy ERC-20 only when enabled and legitimately useful.",parameters:z.object({name:z.string().min(2).max(40),symbol:z.string().min(1).max(10),initialSupplyWholeTokens:z.number().int().positive().max(1_000_000_000),commercialReason:z.string().min(40).max(1000)}),execute:async({name,symbol,initialSupplyWholeTokens,commercialReason})=>{if(!allowOnchainAssetLaunches)throw new Error("Onchain asset launches disabled.");const r=await deployContract("AutonomousToken",[name,symbol,BigInt(initialSupplyWholeTokens)]);appendLedger({kind:"note",usd:0,label:`Utility token ${name}: ${commercialReason}`,txHash:r.txHash});return JSON.stringify({address:r.address,txHash:r.txHash});}});
const nftTool=tool({name:"deploy_nft_collection",description:"Deploy ERC-721 when it is useful to a commercial offer.",parameters:z.object({name:z.string().min(2).max(60),symbol:z.string().min(1).max(10),commercialReason:z.string().min(40).max(1000)}),execute:async({name,symbol,commercialReason})=>{if(!allowOnchainAssetLaunches)throw new Error("Onchain asset launches disabled.");const r=await deployContract("AutonomousNFT",[name,symbol]);appendLedger({kind:"note",usd:0,label:`NFT ${name}: ${commercialReason}`,txHash:r.txHash});return JSON.stringify({address:r.address,txHash:r.txHash});}});

const instructions=`You are Revenue Agent v0.4, a multilingual autonomous digital-commerce operator.
TARGET: real cumulative paid sales USD ${targetUsd} by ${targetDate}. This is an optimization target, never a promise or guaranteed return.
NETWORK: ${networkName}; mainnet enabled=${allowMainnet}.
LOOP: MEASURE -> RESEARCH -> SELECT MARKET -> BUILD/IMPROVE -> PRICE -> PUBLISH -> DISTRIBUTE -> OBSERVE PAID SALES -> SCALE WINNERS -> KILL LOSERS -> REPEAT.
You are not restricted to Spanish or English. Select countries, languages and niches based on commercial evidence. Search in native-language terms when useful. Write natural localized commercial copy, not literal translations. Record language and target market.
Paid sales are the only revenue metric. Never fabricate revenue, customers, reviews, scarcity, affiliations, endorsements or returns. Never promise investment returns or token appreciation. Never copy copyrighted products or impersonate people/brands.
Prefer useful digital products, research briefs, templates, datasets, workflows, calculators, guides, code/data assets, micro-services and agent outputs. NFT/token experiments are optional, not the default.
Read ledger and sales metrics first. If a product sells, prioritize scaling/improving it. If it gets distribution but no sales, change offer/price/market or kill it. Preserve capital. Maximum actual spend per experiment=${maxExperimentUsd}; 24h cap=${maxDailySpendUsd}.
Before creating a product identify buyer pain, where buyers congregate, substitute prices, why the offer is better, and a zero/low-cost distribution path. End every cycle by recording BUILD / SCALE / HOLD / KILL with evidence.`;

export const revenueAgent=new Agent({name:"Revenue Agent v0.4",...(process.env.OPENAI_MODEL?{model:process.env.OPENAI_MODEL}:{}),instructions,tools:[webSearchTool({searchContextSize:"medium"}),walletTool,ledgerTool,noteTool,costTool,productTool,lifecycleTool,marketingTool,tokenTool,nftTool]});
export async function runRevenueAgent(prompt?:string){const result=await run(revenueAgent,prompt??"Run one disciplined commercial cycle. Read ledger and goal pace; research any country/language with strong accessible demand; scale a winner when possible or create at most one product; perform at least one truthful zero-cost distribution action; record BUILD / SCALE / HOLD / KILL.");console.log(result.finalOutput);return result;}
if(import.meta.url===`file://${process.argv[1]}`)runRevenueAgent().catch(e=>{console.error(e);process.exit(1)});
