import fs from "node:fs";
import path from "node:path";
import { encodeFunctionData,parseUnits,type Address } from "viem";
import { clients,loadArtifact,deployContract } from "./blockchain.js";
import { dataDir,treasuryAddress,adminAddress,reinvestBps,usdcAddress,chain } from "./config.js";
const approveAbi=[{type:"function",name:"approve",stateMutability:"nonpayable",inputs:[{name:"spender",type:"address"},{name:"amount",type:"uint256"}],outputs:[{name:"",type:"bool"}]}] as const;
const gatewayMetaPath=path.join(dataDir,"gateway.json");
export function gatewayMetadata():any|null{return fs.existsSync(gatewayMetaPath)?JSON.parse(fs.readFileSync(gatewayMetaPath,"utf8")):null;}
export function resolvedGatewayAddress():Address|undefined{return (process.env.GATEWAY_ADDRESS||gatewayMetadata()?.address) as Address|undefined;}
export function requireGateway():Address{const a=resolvedGatewayAddress();if(!a)throw new Error("RevenueGateway is not deployed yet.");return a;}
export async function ensureGatewayDeployed(){const existing=resolvedGatewayAddress();if(existing)return {address:existing,deployed:false};if(!treasuryAddress)return {address:null,deployed:false,reason:"TREASURY_ADDRESS missing"};if(!adminAddress)return {address:null,deployed:false,reason:"ADMIN_ADDRESS missing"};const {account}=clients();try{const deployed=await deployContract("RevenueGateway",[usdcAddress,treasuryAddress,account.address,adminAddress,reinvestBps]);fs.mkdirSync(dataDir,{recursive:true});const meta={...deployed,blockNumber:deployed.blockNumber.toString(),chainId:chain.id,usdcAddress,treasuryAddress,operatorAddress:account.address,adminAddress,reinvestBps};fs.writeFileSync(gatewayMetaPath,JSON.stringify(meta,null,2));console.log(`[gateway] RevenueGateway deployed: ${deployed.address}`);return {address:deployed.address,deployed:true,txHash:deployed.txHash};}catch(e:any){const reason=e?.shortMessage||e?.message||String(e);console.log(`[gateway] Not deployed yet: ${reason}`);return {address:null,deployed:false,reason};}}
export async function setOnchainProduct(productId:`0x${string}`,priceUsd:number,active=true){const {account,publicClient,walletClient}=clients(),artifact=loadArtifact("RevenueGateway"),txHash=await walletClient.writeContract({address:requireGateway(),abi:artifact.abi,functionName:"setProduct",args:[productId,parseUnits(priceUsd.toFixed(6),6),active],account});await publicClient.waitForTransactionReceipt({hash:txHash});return txHash;}
export async function isOrderPaid(orderId:`0x${string}`){const {publicClient}=clients(),artifact=loadArtifact("RevenueGateway");return await publicClient.readContract({address:requireGateway(),abi:artifact.abi,functionName:"paidOrders",args:[orderId]}) as boolean;}
export function checkoutCalldata(productId:`0x${string}`,orderId:`0x${string}`,priceUsd:number){const gateway=requireGateway(),amount=parseUnits(priceUsd.toFixed(6),6),approveData=encodeFunctionData({abi:approveAbi,functionName:"approve",args:[gateway,amount]}),gatewayAbi=loadArtifact("RevenueGateway").abi,payData=encodeFunctionData({abi:gatewayAbi,functionName:"pay",args:[productId,orderId]});return {usdcAddress,gatewayAddress:gateway,amount:amount.toString(),approveData,payData};}
