import http from "node:http";
import { URL } from "node:url";
import { chain,port,storeName,usdcAddress,treasuryAddress,targetUsd,targetDate,networkName } from "./config.js";
import { listProducts,getProduct,createOrder,getOrderBySecret,salesMetrics } from "./products.js";
import { checkoutCalldata,isOrderPaid,resolvedGatewayAddress } from "./gateway.js";
import { walletSnapshot,treasurySnapshot } from "./blockchain.js";
import { summarizeLedger,goalStatus } from "./ledger.js";
import { ensureAdminToken,requestIsAdmin } from "./admin-auth.js";
function send(res:http.ServerResponse,status:number,body:string,type="text/html; charset=utf-8",headers:any={}){res.writeHead(status,{"content-type":type,"cache-control":"no-store",...headers});res.end(body);}
function json(res:http.ServerResponse,status:number,data:any){send(res,status,JSON.stringify(data,null,2),"application/json; charset=utf-8");}
function esc(s:any){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!));}
async function readBody(req:http.IncomingMessage){let body="";for await(const c of req)body+=c;return body;}
function money(n:number){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(n);}
const contentTypes:any={markdown:["text/markdown; charset=utf-8","md"],text:["text/plain; charset=utf-8","txt"],html:["text/html; charset=utf-8","html"],json:["application/json; charset=utf-8","json"],csv:["text/csv; charset=utf-8","csv"]};
export function startStoreServer(){ensureAdminToken();const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url||"/",`http://${req.headers.host||"localhost"}`);
if(req.method==="GET"&&u.pathname==="/"){const items=listProducts().filter(p=>p.active).map(p=>`<article><h2>${esc(p.title)}</h2><p>${esc(p.description)}</p><small>${esc(p.targetMarket)} · ${esc(p.language)}</small><h3>${money(p.priceUsd)} USDC</h3><a href="/p/${encodeURIComponent(p.slug)}">Buy / Comprar</a></article>`).join("");return send(res,200,`<!doctype html><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><title>${esc(storeName)}</title><style>body{font-family:system-ui;max-width:900px;margin:45px auto;padding:20px;background:#fafafa}article{background:#fff;border:1px solid #ddd;border-radius:16px;padding:22px;margin:18px 0}a,button{padding:12px 18px;background:#111;color:#fff;border:0;border-radius:10px;text-decoration:none}</style><h1>${esc(storeName)}</h1><p>Digital products · USDC on Base</p>${items||"<p>Agent is researching its first market.</p>"}`);}
const pm=u.pathname.match(/^\/p\/([^/]+)$/);if(req.method==="GET"&&pm){const p=getProduct(decodeURIComponent(pm[1]));if(!p||!p.active)return send(res,404,"Product not found");return send(res,200,`<!doctype html><html lang="${esc(p.language)}"><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><title>${esc(p.title)}</title><body style="font-family:system-ui;max-width:760px;margin:45px auto;padding:20px"><h1>${esc(p.title)}</h1><p>${esc(p.description)}</p><small>${esc(p.targetMarket)} · ${esc(p.language)}</small><h2>${money(p.priceUsd)} USDC</h2><button id=buy>Buy with USDC on Base</button><pre id=s></pre><script>const product=${JSON.stringify({id:p.id})};const chainId=${chain.id},chainHex="0x"+chainId.toString(16);async function receipt(h){for(let i=0;i<80;i++){let r=await ethereum.request({method:"eth_getTransactionReceipt",params:[h]});if(r)return r;await new Promise(x=>setTimeout(x,1500))}throw Error("Confirmation timeout")};buy.onclick=async()=>{try{if(!window.ethereum)throw Error("Connect an EVM wallet");s.textContent="Creating order...";let r=await fetch("/api/orders",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({productId:product.id})}),o=await r.json();if(!r.ok)throw Error(o.error);let [from]=await ethereum.request({method:"eth_requestAccounts"}),current=await ethereum.request({method:"eth_chainId"});if(current.toLowerCase()!=chainHex.toLowerCase())await ethereum.request({method:"wallet_switchEthereumChain",params:[{chainId:chainHex}]});s.textContent="Approving USDC...";let a=await ethereum.request({method:"eth_sendTransaction",params:[{from,to:o.usdcAddress,data:o.approveData}]});await receipt(a);s.textContent="Paying...";let h=await ethereum.request({method:"eth_sendTransaction",params:[{from,to:o.gatewayAddress,data:o.payData}]});await receipt(h);location.href=o.downloadUrl}catch(e){s.textContent=e.message||String(e)}};</script></body></html>`);}
if(req.method==="POST"&&u.pathname==="/api/orders"){if(!resolvedGatewayAddress())return json(res,503,{error:"Checkout initializing"});const input=JSON.parse(await readBody(req)||"{}"),p=getProduct(input.productId);if(!p||!p.active)return json(res,404,{error:"product not found"});const order=createOrder(p.id),tx=checkoutCalldata(p.id as `0x${string}`,order.orderId,p.priceUsd);return json(res,200,{orderId:order.orderId,chainId:chain.id,...tx,downloadUrl:`/download/${order.secret}`});}
const dm=u.pathname.match(/^\/download\/([a-f0-9]{64})$/);if(req.method==="GET"&&dm){const order=getOrderBySecret(dm[1]);if(!order)return send(res,404,"Order not found");if(!(await isOrderPaid(order.orderId)))return send(res,402,"<h1>Payment not confirmed yet</h1>");const p=getProduct(order.productId);if(!p)return send(res,404,"Product not found");const [mime,ext]=contentTypes[p.format]||contentTypes.text;return send(res,200,p.content,mime,{"content-disposition":`attachment; filename="${p.slug}.${ext}"`});}
if(req.method==="GET"&&u.pathname==="/admin/login")return send(res,200,`<!doctype html><meta charset=utf-8><body style="font-family:system-ui;max-width:500px;margin:80px auto"><h1>Revenue Agent</h1><form method=post><input style="padding:12px;width:100%" type=password name=token placeholder="Admin token"><button style="margin-top:10px;padding:12px">Open dashboard</button></form></body>`);
if(req.method==="POST"&&u.pathname==="/admin/login"){const token=new URLSearchParams(await readBody(req)).get("token")||"",expected=ensureAdminToken().token;if(token!==expected)return send(res,403,"Invalid token");res.writeHead(302,{"set-cookie":`ra_admin=${encodeURIComponent(token)}; HttpOnly; SameSite=Strict; Path=/; Max-Age=2592000`,location:"/admin"});return res.end();}
if(req.method==="GET"&&u.pathname==="/admin"){if(!requestIsAdmin(req)){res.writeHead(302,{location:"/admin/login"});return res.end();}const [agent,treasury]=await Promise.all([walletSnapshot(),treasurySnapshot()]),ledger=summarizeLedger(),goal=goalStatus(),sales=salesMetrics();return send(res,200,`<!doctype html><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><body style="font-family:system-ui;max-width:1100px;margin:30px auto;padding:20px"><h1>Revenue Agent v0.4</h1><p>${esc(networkName)} · Gateway ${esc(resolvedGatewayAddress()||"waiting")}</p><h2>Paid sales: ${money(ledger.revenueUsd)} / ${money(targetUsd)}</h2><p>Progress ${goal.progressPct}% · Required/day ${money(goal.requiredDailySalesUsd)} · Target ${esc(targetDate)}</p><p><b>Agent:</b> ${esc(agent.address)} · ${esc(agent.usdcBalance)} USDC</p><p><b>Treasury:</b> ${esc(treasuryAddress||"not configured")} · ${esc(treasury?.usdcBalance??"-")} USDC</p><h2>Products</h2><table border=1 cellpadding=8 cellspacing=0><tr><th>Product</th><th>Market</th><th>Language</th><th>Sales</th><th>Revenue</th></tr>${sales.byProduct.map(x=>`<tr><td>${esc(x.title)}</td><td>${esc(x.targetMarket)}</td><td>${esc(x.language)}</td><td>${x.sales}</td><td>${money(x.revenueUsd)}</td></tr>`).join("")}</table></body>`);}
if(req.method==="GET"&&u.pathname==="/api/health")return json(res,200,{ok:true,network:networkName,chainId:chain.id,agentWallet:(await walletSnapshot()).address,treasuryConfigured:!!treasuryAddress,gatewayReady:!!resolvedGatewayAddress(),usdcAddress});
if(req.method==="GET"&&u.pathname==="/robots.txt")return send(res,200,"User-agent: *\nAllow: /\n","text/plain");return send(res,404,"Not found");}catch(e:any){return json(res,500,{error:e?.message||String(e)});}});server.listen(port,()=>console.log(`[web] listening on :${port}`));return server;}
if(import.meta.url===`file://${process.argv[1]}`)startStoreServer();
