import http from "node:http";
import { URL } from "node:url";
import { chain,port,storeName,usdcAddress,treasuryAddress,targetUsd,networkName,pilotMode } from "./config.js";
import { listProducts,getProduct,createOrder,getOrderBySecret,salesMetrics } from "./products.js";
import { checkoutCalldata,isOrderPaid,resolvedGatewayAddress } from "./gateway.js";
import { directCheckoutCalldata,verifyDirectPayment } from "./direct-payment.js";
import { walletSnapshot,treasurySnapshot } from "./blockchain.js";
import { summarizeLedger,goalStatus } from "./ledger.js";
import { ensureAdminToken,requestIsAdmin } from "./admin-auth.js";

function send(res:http.ServerResponse,status:number,body:string,type="text/html; charset=utf-8",headers:any={}){res.writeHead(status,{"content-type":type,"cache-control":"no-store",...headers});res.end(body);}
function json(res:http.ServerResponse,status:number,data:any){send(res,status,JSON.stringify(data,null,2),"application/json; charset=utf-8");}
function esc(s:any){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!));}
async function readBody(req:http.IncomingMessage){let body="";for await(const c of req)body+=c;return body;}
function money(n:number){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(n);}
const contentTypes:any={markdown:["text/markdown; charset=utf-8","md"],text:["text/plain; charset=utf-8","txt"],html:["text/html; charset=utf-8","html"],json:["application/json; charset=utf-8","json"],csv:["text/csv; charset=utf-8","csv"]};
const css=`body{font-family:system-ui,-apple-system,sans-serif;margin:0;background:#f7f7f4;color:#151515}main{max-width:1080px;margin:auto;padding:32px 20px 70px}.hero{padding:48px 0 28px}.hero h1{font-size:clamp(38px,7vw,72px);line-height:.96;margin:0 0 18px}.hero p{font-size:20px;max-width:760px;color:#555}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:18px}.card{background:#fff;border:1px solid #ddd;border-radius:18px;padding:24px}.card h2{margin-top:4px}.price{font-size:28px;font-weight:800}.btn,button{display:inline-block;background:#151515;color:#fff;border:0;border-radius:12px;padding:13px 18px;text-decoration:none;font-size:16px;cursor:pointer}.btn.alt{background:#fff;color:#151515;border:1px solid #bbb}.muted{color:#666}.status{white-space:pre-wrap;margin-top:18px;padding:12px;background:#f0f0ec;border-radius:10px;min-height:20px}code{word-break:break-all}table{width:100%;border-collapse:collapse;background:#fff}th,td{text-align:left;padding:10px;border-bottom:1px solid #eee}.section{margin-top:34px}.tag{display:inline-block;font-size:12px;font-weight:700;letter-spacing:.06em;border:1px solid #bbb;border-radius:999px;padding:5px 9px;margin-bottom:10px}@media(max-width:600px){main{padding:20px 16px}.hero{padding-top:30px}}`;

const stripeOffers=[
  {slug:"audit",kind:"FAST CASH",title:"24-Hour Revenue Leak Audit",desc:"A focused website conversion and offer audit with prioritized fixes, CTA friction, trust gaps and quick revenue wins.",price:"$49 one-time",url:"https://buy.stripe.com/28EcN6bfQbpp1oL0H52VG0m"},
  {slug:"watch",kind:"RECURRING",title:"Competitor Revenue Watch",desc:"Weekly competitor intelligence on pricing, offers, positioning, content and concrete revenue opportunities.",price:"$29/month",url:"https://buy.stripe.com/cNi5kE6ZAdxx0kHahF2VG0n"},
  {slug:"mission",kind:"HIGH TICKET",title:"Custom Branded Mission",desc:"A custom branded real-world mission for a hotel, event, company, tourism business or venue.",price:"$149 one-time",url:"https://buy.stripe.com/cNi00kbfQ2ST0kH3Th2VG0o"}
];

const seoPages:any={
  "/competitor-price-monitoring-service":{tag:"WEEKLY COMPETITOR INTELLIGENCE",title:"Competitor Price Monitoring Service",lead:"Stop manually checking competitor sites. Get a concise weekly report on pricing, offers, positioning, content and promotions, plus concrete revenue opportunities for your business.",bullets:["Track selected competitors every week","Spot pricing, packaging and promotion changes","Turn observations into actionable revenue experiments","Initial report after signup, then weekly delivery"],offer:"watch"},
  "/website-conversion-audit-service":{tag:"24-HOUR CRO AUDIT",title:"Website Conversion Audit Service",lead:"Find the revenue leaks that make qualified visitors leave without buying. Get a prioritized audit focused on offer clarity, CTA friction, trust, pricing and buying flow.",bullets:["Prioritized conversion leaks, not generic advice","Quick wins separated from larger changes","Offer, CTA, trust and pricing observations","Delivered as an actionable revenue plan"],offer:"audit"},
  "/hotel-branded-scavenger-hunt":{tag:"HOTEL & TOURISM REVENUE EXPERIENCE",title:"Branded Scavenger Hunt for Hotels & Resorts",lead:"Turn your property or destination into a branded mission guests can play, share and buy into. Designed for hotels, resorts, tourism businesses, events and venues.",bullets:["Custom narrative and mission concept","Route and challenge structure","Participant instructions","Revenue and upsell ideas for the experience"],offer:"mission"}
};

function stripeCards(){return stripeOffers.map(o=>`<article class=card><div class=tag>${esc(o.kind)}</div><h2>${esc(o.title)}</h2><p>${esc(o.desc)}</p><div class=price>${esc(o.price)}</div><br><a class=btn href="/go/${esc(o.slug)}">Buy securely</a></article>`).join("");}
function seoPage(p:any){const o=stripeOffers.find(x=>x.slug===p.offer)!;return `<!doctype html><html><head><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><title>${esc(p.title)}</title><meta name=description content="${esc(p.lead)}"><link rel=canonical href="${esc(p.path||"")}"><style>${css}</style></head><body><main><a href=/ style="color:#111">← Revenue tools</a><section class=hero><div class=muted>${esc(p.tag)}</div><h1>${esc(p.title)}</h1><p>${esc(p.lead)}</p></section><section class=grid><div class=card><h2>What you get</h2><ul>${p.bullets.map((b:string)=>`<li>${esc(b)}</li>`).join("")}</ul></div><div class=card><div class=tag>${esc(o.kind)}</div><h2>${esc(o.title)}</h2><div class=price>${esc(o.price)}</div><p>${esc(o.desc)}</p><a class=btn href="/go/${esc(o.slug)}">Buy securely with Stripe</a></div></section><section class=section><div class=card><h2>Start free first</h2><p>Use the two-minute Website Revenue Leak Score before buying anything.</p><a class="btn alt" href="/free/revenue-score">Get the free score</a></div></section></main></body></html>`;}

export function startStoreServer(){ensureAdminToken();const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url||"/",`http://${req.headers.host||"localhost"}`);

if(req.method==="GET"&&u.pathname==="/"){
  const items=listProducts().filter(p=>p.active).map(p=>`<article class=card><div class=muted>${esc(p.targetMarket)} · ${esc(p.language)}</div><h2>${esc(p.title)}</h2><p>${esc(p.description)}</p><div class=price>${money(p.priceUsd)} USDC</div><br><a class=btn alt href="/p/${encodeURIComponent(p.slug)}">View digital product</a></article>`).join("");
  return send(res,200,`<!doctype html><html><head><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><title>${esc(storeName)} — Revenue tools and digital products</title><meta name=description content="Practical revenue audits, competitor monitoring, branded experiences and digital products for businesses and individuals."><style>${css}</style></head><body><main><section class=hero><div class=muted>REVENUE TOOLS & DIGITAL SERVICES</div><h1>Find revenue leaks.<br>Act on them fast.</h1><p>Practical services and digital products designed around measurable commercial outcomes. Secure card checkout is available for the featured offers.</p><p><a class=btn href="/free/revenue-score">Get a free Revenue Leak Score</a></p></section><section class=grid>${stripeCards()}</section><section class=section><h2>Solutions by job-to-be-done</h2><section class=grid><article class=card><h2>Monitor competitor pricing</h2><p>Weekly tracking of offers, pricing, positioning and promotions.</p><a href="/competitor-price-monitoring-service">See competitor monitoring</a></article><article class=card><h2>Fix website conversion leaks</h2><p>A prioritized 24-hour CRO and revenue audit.</p><a href="/website-conversion-audit-service">See conversion audit</a></article><article class=card><h2>Monetize guest experiences</h2><p>Custom branded missions for hotels, resorts and tourism.</p><a href="/hotel-branded-scavenger-hunt">See branded missions</a></article></section></section><section class="section"><h2>Instant digital products</h2><section class=grid>${items||"<div class=card>New products are being prepared.</div>"}</section></section></main></body></html>`);
}

if(req.method==="GET"&&u.pathname==="/free/revenue-score"){
  return send(res,200,`<!doctype html><html><head><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><title>Free Website Revenue Leak Score</title><meta name=description content="Score your website for common revenue leaks in under two minutes and see what to fix first."><style>${css}</style></head><body><main><a href=/ style="color:#111">← Revenue tools</a><section class=hero><div class=muted>FREE 2-MINUTE DIAGNOSTIC</div><h1>Website Revenue Leak Score</h1><p>Check the boxes that are true. Your score estimates how many basic conversion elements your site already has.</p></section><div class=card id=q>
  <label><input type=checkbox> A first-time visitor can understand what you sell in 5 seconds.</label><br><br>
  <label><input type=checkbox> Your primary CTA is visible without scrolling.</label><br><br>
  <label><input type=checkbox> Pricing or a clear next step is easy to find.</label><br><br>
  <label><input type=checkbox> You show proof: testimonials, clients, cases, numbers or credentials.</label><br><br>
  <label><input type=checkbox> Your page addresses the top buyer objections.</label><br><br>
  <label><input type=checkbox> Mobile checkout/contact flow is simple.</label><br><br>
  <label><input type=checkbox> Every major page has one obvious commercial action.</label><br><br>
  <label><input type=checkbox> Your offer explains the outcome, not only features.</label><br><br>
  <label><input type=checkbox> You track leads, checkout starts or conversions.</label><br><br>
  <label><input type=checkbox> You actively compare your offer with competitors.</label><br><br>
  <button onclick="score()">Calculate score</button><div class=status id=s></div>
</div><script>function score(){const n=document.querySelectorAll('input:checked').length,p=n*10;let m=p>=80?'Strong foundation. The next gains are likely in offer, pricing, testing and competitive positioning.':p>=50?'Several conversion basics are missing. Fixing the highest-impact gaps may materially improve sales.':'Your site likely has significant conversion leakage. Start with clarity, CTA, trust and offer structure.';s.innerHTML='<b>'+p+'/100</b> — '+m+'<br><br><a class="btn" href="/go/audit">Get the full 24-Hour Revenue Leak Audit — $49</a><br><br><a href="/go/watch">Or monitor competitors weekly — $29/month</a>';}</script></main></body></html>`);
}

if(req.method==="GET"&&seoPages[u.pathname]){const p={...seoPages[u.pathname],path:`https://${req.headers.host}${u.pathname}`};return send(res,200,seoPage(p));}

const go=u.pathname.match(/^\/go\/(audit|watch|mission)$/);
if(req.method==="GET"&&go){const o=stripeOffers.find(x=>x.slug===go[1]);if(!o)return send(res,404,"Offer not found");console.log(`[checkout-click] ${o.slug} ref=${u.searchParams.get("ref")||req.headers.referer||"direct"}`);res.writeHead(302,{location:o.url,"cache-control":"no-store"});return res.end();}

const pm=u.pathname.match(/^\/p\/([^/]+)$/);
if(req.method==="GET"&&pm){
  const p=getProduct(decodeURIComponent(pm[1]));if(!p||!p.active)return send(res,404,"Product not found");
  const paymentText=pilotMode?"Pay directly in USDC on Base — funds go to the seller treasury.":"Pay with USDC on Base.";
  return send(res,200,`<!doctype html><html lang="${esc(p.language)}"><head><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><title>${esc(p.title)}</title><meta name=description content="${esc(p.description)}"><meta property="og:title" content="${esc(p.title)}"><meta property="og:description" content="${esc(p.description)}"><style>${css}</style></head><body><main><a href=/ style="color:#111">← Store</a><section class=hero><div class=muted>${esc(p.targetMarket)} · ${esc(p.language)}</div><h1>${esc(p.title)}</h1><p>${esc(p.description)}</p></section><div class=card><div class=price>${money(p.priceUsd)} USDC</div><p>${paymentText}</p><button id=buy>Buy & unlock</button><div class=status id=s></div></div><script>
const product=${JSON.stringify({id:p.id,slug:p.slug,priceUsd:p.priceUsd})};
const chainId=${chain.id};const chainHex="0x"+chainId.toString(16);const pilot=${JSON.stringify(pilotMode)};
async function receipt(h){for(let i=0;i<90;i++){const r=await ethereum.request({method:"eth_getTransactionReceipt",params:[h]});if(r)return r;await new Promise(x=>setTimeout(x,1500))}throw Error("Confirmation timeout")}
async function switchChain(){const current=await ethereum.request({method:"eth_chainId"});if(current.toLowerCase()===chainHex.toLowerCase())return;try{await ethereum.request({method:"wallet_switchEthereumChain",params:[{chainId:chainHex}]})}catch(e){if(e.code===4902){await ethereum.request({method:"wallet_addEthereumChain",params:[{chainId:chainHex,chainName:${JSON.stringify(chain.name)},nativeCurrency:{name:"ETH",symbol:"ETH",decimals:18},rpcUrls:[${JSON.stringify(chain.rpcUrls.default.http[0])}],blockExplorerUrls:["https://basescan.org"]}]})}else throw e}}
buy.onclick=async()=>{const st=document.getElementById("s");try{if(!window.ethereum)throw Error("A Base-compatible wallet is required for this pilot checkout.");const [from]=await ethereum.request({method:"eth_requestAccounts"});await switchChain();st.textContent="Creating secure order…";let r=await fetch("/api/orders",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({productId:product.id,payer:from})});let o=await r.json();if(!r.ok)throw Error(o.error||"Order error");if(pilot){st.textContent="Sending "+product.priceUsd+" USDC directly to seller treasury…";const h=await ethereum.request({method:"eth_sendTransaction",params:[{from,to:o.to,data:o.data}]});st.textContent="Payment sent. Waiting for confirmation…";await receipt(h);st.textContent="Verifying payment and unlocking product…";let vr=await fetch("/api/verify",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({secret:o.secret,txHash:h})});let v=await vr.json();if(!vr.ok)throw Error(v.error||"Verification failed");location.href=o.downloadUrl}else{st.textContent="Approving USDC…";let a=await ethereum.request({method:"eth_sendTransaction",params:[{from,to:o.usdcAddress,data:o.approveData}]});await receipt(a);st.textContent="Paying…";let h=await ethereum.request({method:"eth_sendTransaction",params:[{from,to:o.gatewayAddress,data:o.payData}]});await receipt(h);location.href=o.downloadUrl}}catch(e){st.textContent=e.message||String(e)}};
</script></main></body></html>`);
}

if(req.method==="POST"&&u.pathname==="/api/orders"){
  if(!treasuryAddress)return json(res,503,{error:"Treasury is not configured"});
  const input=JSON.parse(await readBody(req)||"{}"),p=getProduct(input.productId);if(!p||!p.active)return json(res,404,{error:"product not found"});
  if(pilotMode){if(!/^0x[a-fA-F0-9]{40}$/.test(String(input.payer||"")))return json(res,400,{error:"payer wallet required"});const order=createOrder(p.id,String(input.payer),p.priceUsd),tx=directCheckoutCalldata(p.priceUsd);return json(res,200,{orderId:order.orderId,secret:order.secret,chainId:chain.id,...tx,downloadUrl:`/download/${order.secret}`});}
  if(!resolvedGatewayAddress())return json(res,503,{error:"Checkout initializing"});
  const order=createOrder(p.id,String(input.payer||""),p.priceUsd),tx=checkoutCalldata(p.id as `0x${string}`,order.orderId,p.priceUsd);return json(res,200,{orderId:order.orderId,secret:order.secret,chainId:chain.id,...tx,downloadUrl:`/download/${order.secret}`});
}

if(req.method==="POST"&&u.pathname==="/api/verify"){
  if(!pilotMode)return json(res,400,{error:"Direct verification only available in pilot mode"});
  const input=JSON.parse(await readBody(req)||"{}");if(!/^0x[a-fA-F0-9]{64}$/.test(String(input.txHash||"")))return json(res,400,{error:"valid transaction hash required"});
  const result=await verifyDirectPayment(String(input.secret||""),input.txHash);return json(res,200,result);
}

const dm=u.pathname.match(/^\/download\/([a-f0-9]{64})$/);
if(req.method==="GET"&&dm){const order=getOrderBySecret(dm[1]);if(!order)return send(res,404,"Order not found");const paid=pilotMode?!!order.paid:await isOrderPaid(order.orderId);if(!paid)return send(res,402,"<h1>Payment not confirmed yet</h1><p>Return after the blockchain transaction is confirmed.</p>");const p=getProduct(order.productId);if(!p)return send(res,404,"Product not found");const [mime,ext]=contentTypes[p.format]||contentTypes.text;return send(res,200,p.content,mime,{"content-disposition":`attachment; filename="${p.slug}.${ext}"`});}

if(req.method==="GET"&&u.pathname==="/sitemap.xml"){const base=`https://${req.headers.host}`;const productUrls=listProducts().filter(p=>p.active).map(p=>`<url><loc>${base}/p/${encodeURIComponent(p.slug)}</loc><lastmod>${p.updatedAt}</lastmod></url>`).join("");const seoUrls=Object.keys(seoPages).map(path=>`<url><loc>${base}${path}</loc></url>`).join("");return send(res,200,`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>${base}/</loc></url><url><loc>${base}/free/revenue-score</loc></url>${seoUrls}${productUrls}</urlset>`,`application/xml; charset=utf-8`);}
if(req.method==="GET"&&u.pathname==="/robots.txt")return send(res,200,"User-agent: *\nAllow: /\nSitemap: https://"+(req.headers.host||"")+"/sitemap.xml\n","text/plain");

if(req.method==="GET"&&u.pathname==="/admin/login")return send(res,200,`<!doctype html><meta charset=utf-8><style>${css}</style><main><h1>Revenue Agent</h1><form method=post><input style="padding:12px;width:100%;box-sizing:border-box" type=password name=token placeholder="Admin token"><br><br><button>Open dashboard</button></form></main>`);
if(req.method==="POST"&&u.pathname==="/admin/login"){const token=new URLSearchParams(await readBody(req)).get("token")||"",expected=ensureAdminToken().token;if(token!==expected)return send(res,403,"Invalid token");res.writeHead(302,{"set-cookie":`ra_admin=${encodeURIComponent(token)}; HttpOnly; SameSite=Strict; Path=/; Max-Age=2592000`,location:"/admin"});return res.end();}
if(req.method==="GET"&&u.pathname==="/admin"){if(!requestIsAdmin(req)){res.writeHead(302,{location:"/admin/login"});return res.end();}const [agent,treasury]=await Promise.all([walletSnapshot(),treasurySnapshot()]),ledger=summarizeLedger(),goal=goalStatus(),sales=salesMetrics();return send(res,200,`<!doctype html><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><style>${css}</style><main><h1>Revenue Agent — Pilot</h1><p>${esc(networkName)} · ${pilotMode?"DIRECT USDC PILOT":"GATEWAY"}</p><div class=grid><div class=card><div>Paid sales</div><div class=price>${money(ledger.revenueUsd)}</div></div><div class=card><div>Target</div><div class=price>${money(targetUsd)}</div><div>${goal.progressPct}%</div></div><div class=card><div>Sales</div><div class=price>${sales.totalSales}</div></div><div class=card><div>Required/day</div><div class=price>${money(goal.requiredDailySalesUsd)}</div></div></div><h2>Treasury</h2><div class=card><code>${esc(treasuryAddress||"not configured")}</code><p>${esc(treasury?.usdcBalance??"-")} USDC</p></div><h2>Products</h2><table><tr><th>Product</th><th>Market</th><th>Language</th><th>Sales</th><th>Revenue</th></tr>${sales.byProduct.map(x=>`<tr><td>${esc(x.title)}</td><td>${esc(x.targetMarket)}</td><td>${esc(x.language)}</td><td>${x.sales}</td><td>${money(x.revenueUsd)}</td></tr>`).join("")}</table><p class=muted>Operational wallet: <code>${esc(agent.address)}</code></p></main>`);}

if(req.method==="GET"&&u.pathname==="/api/health")return json(res,200,{ok:true,mode:pilotMode?"pilot-direct-usdc":"gateway",network:networkName,chainId:chain.id,agentWallet:(await walletSnapshot()).address,treasuryConfigured:!!treasuryAddress,checkoutReady:pilotMode?!!treasuryAddress:!!resolvedGatewayAddress(),usdcAddress,products:listProducts().filter(p=>p.active).length});
return send(res,404,"Not found");
}catch(e:any){return json(res,500,{error:e?.message||String(e)});}});server.listen(port,()=>console.log(`[web] listening on :${port}`));return server;}
if(import.meta.url===`file://${process.argv[1]}`)startStoreServer();